FROM nginx:alpine
LABEL maintainer="Aeries Technology"
RUN mkdir /DHS_IT_BOT
#RUN chown -R www:www /var/lib/nginx
RUN chown -R root:root /DHS_IT_BOT
#COPY deliveranswers.conf /etc/nginx/sites-enabled/default.conf
COPY chatbot.conf /etc/nginx/conf.d/chatbot.conf
#RUN rm /etc/nginx/conf.d/default.conf
COPY DHS_IT_BOT /DHS_IT_BOT
EXPOSE 80



FROM python:3.12.3
# Set the working directory
WORKDIR /DHS
# Copy the project code into the container
COPY DHS /DHS
# Install dependencies
RUN pip install --upgrade pip
RUN pip install -r /DHS/dhs_api/requirement.txt
EXPOSE 8000