CREATE DATABASE dhs_db;
\connect dhs_db; 
CREATE TABLE IF NOT EXISTS conversation_history
		(
		    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
		    user_input text  NOT NULL,
		    bot_response text  NOT NULL,
		    created_at timestamp with time zone NOT NULL,
		    CONSTRAINT conversation_history_pkey PRIMARY KEY (id)
		);
CREATE TABLE IF NOT EXISTS user_feedback
		(
		    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
		    user_email character varying(100) ,
		    ratings integer,
		    reviews text ,
		    created_at timestamp with time zone NOT NULL,
		    CONSTRAINT user_feedback_pkey PRIMARY KEY (id)
		);